AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Eventual bank transfer simulator
  
Globals:
  Function:
    Timeout: 10

Resources:
  TransferSimulatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dynamo-handler/
      Handler: app.handler
      Runtime: nodejs18.x
      Policies:
        - SQSSendMessagePolicy:
            QueueName: account_transfer
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 minute)" 
      Environment:
        Variables:
          # 1 tps
          NUMBER_OF_TRANSFERS: 60
          QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/account_transfer"

Outputs:
  Function:
    Description: "Transfer simulator function ARN"
    Value: !GetAtt TransferSimulatorFunction.Arn
